# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hq6OFZAiNdvGzvazQ_FzEDNI7Kdt9NvJ
"""

import pandas as pd
import numpy as np

print(' Hello Capstone Project Course!')

